services:
  caddy:
    image: docker.io/library/caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/caddy:/etc/caddy:Z,U
      - ./data/caddy:/data:Z,U
      - ./config/caddy:/config:Z,U
    extra_hosts:
      - "host.containers.internal:host-gateway"
