services:
  microbin:
    image: docker.io/danielszabo99/microbin:latest
    container_name: microbin
    restart: always
    ports:
     - "3004:8080"
    volumes:
      - ./data/microbin:/app:Z,U
    environment:
      - MICROBIN_BASIC_AUTH_USERNAME
      - MICROBIN_BASIC_AUTH_PASSWORD
      - MICROBIN_ADMIN_USERNAME
      - MICROBIN_ADMIN_PASSWORD
      - MICROBIN_EDITABLE
      - MICROBIN_FOOTER_TEXT
      - MICROBIN_HIDE_FOOTER
      - MICROBIN_HIDE_HEADER
      - MICROBIN_HIDE_LOGO
      - MICROBIN_NO_LISTING
      - MICROBIN_HIGHLIGHTSYNTAX
      - MICROBIN_BIND
      - MICROBIN_PRIVATE
      - MICROBIN_PURE_HTML
      - MICROBIN_DATA_DIR=pasta_data
      - MICROBIN_JSON_DB=true
      - MICROBIN_PUBLIC_PATH
      - MICROBIN_SHORT_PATH
      - MICROBIN_READONLY
      - MICROBIN_UPLOADER_PASSWORD
      - MICROBIN_SHOW_READ_STATS
      - MICROBIN_TITLE
      - MICROBIN_THREADS
      - MICROBIN_GC_DAYS
      - MICROBIN_ENABLE_BURN_AFTER
      - MICROBIN_DEFAULT_BURN_AFTER
      - MICROBIN_WIDE
      - MICROBIN_QR
      - MICROBIN_ETERNAL_PASTA
      - MICROBIN_ENABLE_READONLY
      - MICROBIN_DEFAULT_EXPIRY
      - MICROBIN_NO_FILE_UPLOAD
      - MICROBIN_CUSTOM_CSS
      - MICROBIN_HASH_IDS
      - MICROBIN_ENCRYPTION_CLIENT_SIDE
      - MICROBIN_ENCRYPTION_SERVER_SIDE
      - MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB
      - MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB
