services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - ./data/caddy:/data
      - ./config/caddy:/config
    extra_hosts:
      - "host.containers.internal:host-gateway"

volumes:
  caddy_data:
  caddy_config:
